spring:
  application:
    name: "erp_v1"

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/Erp}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update   
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 9001